// <auto-generated />
namespace WaveFit2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.0-preview2-24180-01")]
    public sealed partial class AddHealthCenter_Audiometer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHealthCenter_Audiometer));
        
        string IMigrationMetadata.Id
        {
            get { return "202405211841054_AddHealthCenter_Audiometer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
