; To the translator:
;
; Only translate text in double "quotes". Two double quotes in the middle
; of a string indicates start of new line. Don't use double quotes as a
; part of the translation, single 'quotes' are allowed. Use a Windows editor
; like NOTEPAD from Accessories to edit this file. Don't use DOS editors
; (They use another character set.) The editor must NOT insert special
; format characters like Word Perfect, MS Word and WRITE from Accessories
; does.
;
; Translations send to Madsen Electronics, DK will be added in next release.

[HIPROTST text]
SwitchBox      = "Avec Switch Box de chez Madsen Electronics ?"
AURICALSwitch  = "Avec HI-PRO via AURICAL ?"
YES            = "Oui"
NO             = "Non"
Internal       = "Interne"
External       = "Externe"
Error          = "Erreur"
Title          = "Test HI-PRO"
Test           = "Test"
Exit           = "Quitter"
OK             = "OK"
Help           = "Aide"
Searching      = "Recherche"
SelftestError1 = "Erreur : %06lXH"
SelftestError2 = "Appelez le support technique!"
ComPortNotInst = "Le port COM n'est pas instappé"
Abort          = "Abandon"
Aborted        = "Abandon"
MenuLine1      = "1) Vérifiez que HI-PRO est relié à l'ordinateur."
MenuLine2      = "2) Vérifiez que HI-PRO est en marche et que le voyant de mise sous tension"
MenuLine3      = "   est allumé. (A la mise en route, les voyants proches des connecteurs de"
MenuLine4      = "   la face avant clignotent une fois pour indiquer qu'une autovérification"
MenuLine5      = "   a été lancée.)"
MenuLine6      = "3) Appuyez sur le bouton 'Test' pour lancer le test, et sur le bouton"
MenuLine7      = "   'OK' pour sortir du programme de test."
MenuLine8      = ""
MenuLine9      = "Port de comm.                 : "
MenuLine10     = "Port de switch box.           : "
MenuLine11     = "Vitesse de transmission (Max) : "
MenuLine12     = "Version progiciel HI-PRO      : "
MenuLine13     = "Version monitor HI-PRO        : "
MenuLine14     = "Etat autovérification         : "
SerialNo       = "SN                            : "

[ERRORS]
Error010 = "Erreur de cadre, rapporté par HI-PRO"
Error011 = "Erreur récepteur occupé, rapporté par HI-PRO"
Error012 = "Erreur bruit de ligne sur le récepteur, rapporté par HI-PRO"
Error015 = "Erreur délai d'attente récepteur, rapporté par HI-PRO"
Error020 = "Numéro de message non valable, rapporté par HI-PRO"
Error021 = "En-tête de message non valable, rapporté par HI-PRO"
Error022 = "Données non valables, rapporté par HI-PRO"
Error023 = "Erreur message de terminaison, rapporté par HI-PRO"
Error030 = "Trop de caractères dans l'argument, rapporté par HI-PRO"
Error031 = "Pas assez de données dans le flot de l'argument, rapporté par HI-PRO"
Error032 = "Trop de données dans le flot de l'argument, rapporté par HI-PRO"
Error033 = "Argument des données en dehors de la gamme acceptable, rapporté par HI-PRO"
Error034 = "Trop peu de données dans le bloc de données octet hex, rapporté par HI-PRO"
Error035 = "Donnée recherchée non disponible, rapporté par HI-PRO"
Error036 = "Données non valables dans le tampon d'entrée, rapporté par HI-PRO"
Error037 = "Mode de communication non valable, rapporté par HI-PRO"
Error038 = "Synchronisation trop rapide, rapporté par HI-PRO"
Error040 = "Mémoire insuffisante, rapporté par HI-PRO"
Error041 = "Le mode apprentissage (learn) n'est pas lancé, rapporté par HI-PRO"
Error042 = "Déjà en mode apprentissage (learn), rapporté par HI-PRO"
Error043 = "Flot des digits de sortie non défini, rapporté par HI-PRO"
Error044 = "Spécification d'entrée non définie, rapporté par HI-PRO"
Error045 = "Désignation des broches non définie, rapporté par HI-PRO"
Error046 = "Delai d'attent H.I., rapporté par HI-PRO"
Error047 = "Le HI-PRO connecté n'a pas pu être authentifié (Authentification d'appareil). Veuillez contacter votre fournisseur pour demander de l'aide"
Error048 = "La mémoire tampon est pleine, rapporté par HI-PRO"
Error049 = "Dépassement de délai ADC signalé par HI-PRO"
Error050 = "Erreur somme de contrôle, rapporté par HI-PRO"
Error051 = "Erreur vérification flash, rapporté par HI-PRO"
Error052 = "Programme chargé non valable, rapporté par HI-PRO"
Error099 = "Erreur indéfinie, rapporté par HI-PRO"
Error200 = "DELAI ECOULE""HI-PRO ne répond pas""Vérifiez les connexions de l'alimentation et de l'interface RS 232"
Error201 = "Erreur dans WriteComm""GetCommError retour %d"
Error202 = "Erreur dans OpenComm""COM port est peut-être utilisé par un autre périphérique. Essayez de changer COMPort= dans HIPRO.INI."
Error203 = "Erreur dans SetCommState"
Error204 = "Erreur dans BuildCommDCB"
Error205 = "L'utilisateur n'a pas ouvert de session"
Error206 = "HI-PRO a été réinitialisé (réglages effacés)"
Error207 = "Données non valables reçues de HI-PRO"
Error208 = "En-tête non valable reçu de HI-PRO"
Error209 = "Flot trop important reçu de HI-PRO"
Error210 = "Valeurs numériques hors-gamme, reçues de HI-PRO"
Error211 = "Pas de caractère de terminaison dans les données reçues de HI-PRO"
Error212 = "Blocs incomplets reçus de HI-PRO"
Error213 = "Erreur dans ReadComm""GetCommError retour %d"
Error214 = "Données inattendues, reçues de HI-PRO"
Error215 = "Somme de vérification incorrecte dans les données reçues de HI-PRO"
Error216 = "Erreur dans CloseComm"
Error217 = "Paramètres incorrects envoyés au gestionnaire de l'instrument"
Error218 = "Tension accu faible. Débrancher HI de HI-PRO"
Error219 = "Etat d'erreur de l'autovérification"
Error221 = "Débordement du récepteur""Tampon d'entrée trop petit ou non vidé"
Error222 = "Limite de fonctionnement dépassée""Interruptions annulées trop longtemps. Essayer une vitesse de transmission pl"
Error223 = "Erreur de parité"
Error224 = "Erreur de cadre""Mauvais instrument relié ou instrument à l'arrêt"
Error225 = "Coupure détectée""Mauvais instrument relié ou instrument à l'arrêt"
Error226 = "Queue d'attente pour la transmission trop longue""Tampon de sortie trop petit"
Error227 = "Le mode requis n'est pas disponible, ou le paramètre idComDev n'est pas valable"
Error228 = "La file d'attente de transmission ne se vide jamais ! Possibilité de conflit IRQ"
Error229 = "Le HI-PRO connecté n'a pas pu être authentifié (Authentification de pilote PC). Veuillez contacter votre fournisseur pour demander de l'aide"
Error255 = "Erreur inconnue"
